steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcpd-294815/github.com', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcpd-294815/github.com']
images: ['gcr.io/gcpd-294815/github.com']