openapi: 3.0.0
info:
  version: v1
  title: My API
  host: gcpd-294815.appspot.com
paths:
  /LaborExchange/api/companytypes:
    get:
      tags:
        - LaborExchange
      operationId: CompanyTypesGetAll
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
            application/json:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
            text/json:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
  "/LaborExchange/api/companytype/id/{id}":
    get:
      tags:
        - LaborExchange
      operationId: CompanyTypesGetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
            application/json:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
            text/json:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
  "/LaborExchange/api/companytypes/page/{page}/pagecount/{pagecount}":
    get:
      tags:
        - LaborExchange
      operationId: CompanyTypesGetByPageAndPagecount
      parameters:
        - name: page
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: pagecount
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
            application/json:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object
            text/json:
              schema:
                uniqueItems: false
                type: array
                items:
                  type: object